### ISSUE TITLE
Vine in beisswurms

### ISSUE THREAD

**Issue by HanryuDR** [GenieClient/Maps#28]
After climbing up the rope ladder for several long moments, you eventually reach the top.

[Abandoned Mine, Entrance]
Gigantic boulders are strewn all over, steep rock faces surround this area and a large hole lies in the ground.  Firmly secured to several of the boulders is a rope ladder.  Other than the sinkhole, there do not appear to be any obvious exits.
You also see a strong creeper.
Obvious paths: none.
Roundtime: 14 sec.
R> 
Mapped exits: climb ladder, climb creeper
...wait 14 seconds.
R> 
...wait 13 seconds.
R> 
Timer: 5
R> 
You feel fully rested.
R> 
Timer: 6
Timer: 7
R> 
Timer: 8
Timer: 9
Timer: 10
Timer: 11
R> 
Timer: 12
Timer: 13
Timer: 14
R> 
Timer: 15
Timer: 16
Timer: 17
> 
Timer: 18

*** Retry movement

Timer: 19
Timer: 20
Timer: 21
Timer: 22
Timer: 23
> [automapper]: climb creeper
Timer: 24
You almost make it to the top of the rock face before losing your grip!
The ground approaches you at an alarming rate!  SPLAT!

[Roundtime: 5 seconds]

**Comment by HanryuDR** [comment]
> 
You run east.
[Abandoned Mine, Tunnel]
More rich veins of ore and crystals in the rock face attract the eye and emphasize the wealth of unmined deposits in this tunnel.  Hanging from the ledge is a rope.
You also see an alabaster stone, a small tin nugget, an alabaster pebble, a small tin nugget, an alabaster pebble, an alabaster pebble, a beisswurm, a beisswurm, a small alabaster rock and a beisswurm.
Also here: Wirks.
Obvious exits: east, west.
> 
Mapped exits: climb rope
[automapper]: climb ladder
[Abandoned Mine, Ledge]
More shining deposits glitter before your eyes.  Making a mental note of the exact location, you consider returning with the correct tools to mine these rich deposits.  High above shines a faint light, possibly the exit from the mine.  A rope ladder dangles above you. 
You also see a large copper nugget, a marble stone, a small marble rock, a marble pebble and a rope.
Also here: Mirks.
Obvious exits: none.
> 
Mapped exits: climb rope, climb ladder
[automapper]: climb creeper
After climbing up the rope ladder for several long moments, you eventually reach the top.

[Abandoned Mine, Entrance]
Gigantic boulders are strewn all over, steep rock faces surround this area and a large hole lies in the ground.  Firmly secured to several of the boulders is a rope ladder.  Other than the sinkhole, there do not appear to be any obvious exits.
You also see a strong creeper.
Also here: Angat.
Obvious paths: none.
Roundtime: 15 sec.
R> 
Mapped exits: climb ladder, climb creeper
...wait 15 seconds.
R> 
Timer: 4
Timer: 5
Timer: 6
You feel fully rested.
R> 
Timer: 7
Timer: 8
Timer: 9
Timer: 10
R> 
Timer: 11
Timer: 12
R> 
Timer: 13
Timer: 14
Timer: 15
Timer: 16
Timer: 17
Timer: 18
Timer: 19

*** Retry movement

Timer: 20
Timer: 21
> [automapper]: climb creeper
Timer: 22
You scamper up and over the rock face.

[Mountainous Route]
Loose rocks from recent landslides cover the trail making progress slightly more precarious and slower.  A strong creeper seems to have won a battle with the steep cliff face and secured holds in the rock as far up as you can see.  
Obvious paths: east, up.
[Roundtime: 7 seconds]
R> 
Mapped exits: climb creeper
R> 
Timer: 23
Timer: 24
Timer: 25
Nutrition just arrived.
R> 
Nutrition runs up.
R> 
Timer: 26
Timer: 27
Timer: 28
Timer: 29
[automapper]: east
[automapper]: down
> 
Timer: 30
You plod east.
[Lairocott Brach, Entrance]
Placed in the wall of the sheer cliff is a huge stone door with an arched top.  Two large lifelike sentinels, one on either side of the door, stand at attention in silence.
You also see a dusky raven.
Obvious paths: west, down.

**Comment by Azothy** [comment]
Fixed in latest Automapper and Maps
