### ISSUE TITLE
Searches suck, fix them

### ISSUE THREAD

**Issue by HanryuDR** [GenieClient/Maps#34]
Types of Searches:
Roundtime Search: Search until the path is found *without the text* "some signs there may be" included. This path will usually vanish when someone takes it, so someone could steal your search efforts and require you to find it all over again! This path will usually remain in $roomobjs until someone takes it (unknown if there is a timer on it fading on its own.) See Leucro/Viper/Guardian/Geni entrance for most examples.

Roundtime Search, invisible path: Possibly the same as above, but this path will not show up in $roomobjs. See Forest Geni access.

Object Search: Search the object, no roundtime. Further searching of the object results in "You notice <path>!"

No-RT Search, with temp $roomobjs: One search will display a unique message. On a short timer, you can LOOK at the room to see the path in $roomobjs (which vanishes after less than 1 second); this type of path can be POINTED out to others in the room. Until the timer expires, further searching will result in normal searching with RT. This type of search requires a perception check and failure causes roundtime.

No-RT Search, invisible path: One search will display a unique message. From there, go through the revealed path. Further searching will result in normal searching with RT. $roomobjs is not populated at all. Unknown if there is a timer to take the discovered path.

...Maps\Map11_Vipers_Rock_Guardians.xml (14 hits)
	Line 7:     <arc exit="go" move="search go faint path" destination="2" />
You search around for a moment.
Roundtime: 3 sec.
You find a faint path. ($roomobjs)
You find faint traces of an animal trail and a faint path. ($roomobjs)
	Line 8:     <arc exit="go" move="search go animal trail" destination="3" />
You search around for a moment.
Roundtime: 3 sec.
You find faint traces of an animal trail. ($roomobjs)
	Line 21:     <arc exit="go" move="search go faint trail" destination="4" />
You search around for a moment.
Roundtime: 3 sec.
You find very faint traces of an animal trail. ($roomobjs)
	Line 27:     <arc exit="go" move="search go animal trail" destination="5" />
You search around for a moment.
Roundtime: 3 sec.
You find a faint animal trail. ($roomobjs)
	Line 32:     <arc exit="go" move="search go bare spot" destination="6" />
You search around for a moment.
Roundtime: 3 sec.
You find a bare spot that leads southeast into the deep wilderness and some faint animal tracks. ($roomobjs)
	Line 34:     <arc exit="go" move="search go faint tracks" destination="36" />
You search around for a moment.
Roundtime: 3 sec.
You find a bare spot that leads southeast into the deep wilderness and some faint animal tracks. ($roomobjs)
	Line 293:     <arc exit="go" move="search go animal tracks" destination="5" />
You search around for a moment.
Roundtime: 3 sec.
You find some animal tracks. ($roomobjs)
	Line 498:     <arc exit="go" move="search go narrow gap" destination="68" />
You search around for a moment.
Roundtime: 3 sec.
You find a narrow gap. ($roomobjs)
	Line 504:     <arc exit="go" move="search go narrow gap" destination="67" />
You search around for a moment.
Roundtime: 3 sec.
You find a narrow gap. ($roomobjs)
	Line 510:     <arc exit="go" move="search go narrow crevice" destination="70" />
You search around for a moment.
Roundtime: 3 sec.
You find a narrow crevice. ($roomobjs)
	Line 515:     <arc exit="go" move="search go narrow crevice" destination="69" />
You search around for a moment.
Roundtime: 3 sec.
You find a narrow crevice. ($roomobjs)
	Line 719:     <arc exit="go" move="search go faint trail" destination="105" />
You search around for a moment.
Roundtime: 3 sec.
You find a faint trail. (NOT IN ROOMOBJS)
	Line 732:     <arc exit="go" move="search go faint trail" destination="112" />
You search around for a moment.
Roundtime: 3 sec.
You find a faint trail. (NOT IN ROOMOBJS)
	Line 850:     <arc exit="go" move="search go faint trail" destination="103" />
You search around for a moment.
Roundtime: 3 sec.
You find a faint trail. (NOT IN ROOMOBJS)

...Maps\Map150_Fang_Cove.xml (2 hits)
	Line 434:     <arc exit="go" move="objsearch back.wall go narrow gap" destination="64" />
You search around, closely examining the dark back wall.  Nodding in satisfaction, you find a narrow gap in the stone that leads deeper into the cave! (NO RT) 
You notice a narrow gap in the stone that leads deeper into the cave!
	Line 656:     <arc exit="go" move="objsearch creeper go cave" destination="95" />
You search around, closely examining some thick creepers.  Nodding in satisfaction, you find a small cave! (NO RT)
You notice a small cave!

...Maps\Map1_Crossing.xml (1 hit)
	Line 2902:     <arc exit="go" move="search go stone portal" destination="1007" />
After a careful search of the area, you discover a stone portal! (NO RT) ($roomobjs)

...Maps\Map30_Riverhaven.xml (1 hit)
	Line 2552:     <arc exit="go" move="-search shadow;-go opening" destination="423" />
You search around, closely examining some deep shadows.  Nodding in satisfaction, you find an opening at the base of the wall! (NO RT)
You notice an opening at the base of the wall!

...Maps\Map33a_Road_to_Therenborough.xml (3 hits)
	Line 79:     <arc exit="climb" move="objsearch rocky.ledge climb shrub" destination="11" />
You search around, closely examining a rocky ledge.  Nodding in satisfaction, you find some sturdy shrubs clinging to the rock face! (NO RT) 
You notice some sturdy shrubs clinging to the rock face!
	Line 91:     <arc exit="climb" move="objsearch outcropping climb handholds" destination="13" />
You search around, closely examining a rocky outcropping.  Nodding in satisfaction, you find some irregular handholds! (NO RT)
You notice some irregular handholds!
	Line 103:     <arc exit="climb" move="objsearch outcrop climb handholds" destination="13" />
You search around, closely examining a rocky outcropping.  Nodding in satisfaction, you find some irregular handholds! (NO RT)
You notice some irregular handholds! 

...Maps\Map34_Mistwood_Forest.xml (2 hits)
	Line 596:     <arc exit="climb" move="objsearch rubble climb stairway" destination="155" /> -- You search around, closely examining a pile of scattered rubble.  Nodding in satisfaction, you find a dark stairway! (NO RT) 
You notice a dark stairway!
	Line 859:     <arc exit="climb" move="objsearch ravine ; climb crack" destination="138" />
You search around, closely examining a deep ravine.  Nodding in satisfaction, you find a series of shallow cracks!  (NO RT) 
You notice a series of shallow cracks!

...Maps\Map40_Langenfirth_to_Therenborough.xml (1 hit)
	Line 937:     <arc exit="go" move="search go forest trail" destination="137" />
You push through bushes and around shrubbery and discover a faint forest trail! (NO RT) ($roomobjs)

...Maps\Map4a_Tiger_Clan.xml (1 hit)
	Line 81:     <arc exit="none" move="search go faint trail" destination="73" />
You search around for a moment.
Roundtime: 4 sec.
You find a very faint trail through the grass. ($roomobjs)

...Maps\Map4_Crossing_West_Gate.xml (1 hit)
	Line 2645:     <arc exit="go" move="search go trampled path" destination="482" />
After a careful search of the area, you discover a trampled path! (NO RT) ($roomobjs)

...Maps\Map7_NTR.xml (5 hits)
	Line 1419:     <arc exit="climb" move="search climb ladder" destination="170" />
You search around for a moment.
Roundtime: 3 sec.
Hidden inside an alcove behind the staircase is an old ladder.  It leads down. (NOT IN ROOMOBJS)
	Line 2767:     <arc exit="go" move="search go concealed path" destination="479" />
You notice a path hidden in the brush that leads under the stone bridge. (NO RT) ($roomobjs)
	Line 2904:     <arc exit="go" move="search go overgrown path" destination="397" />
There seems to be some sort of path leading to the east. (NO RT) ($roomobjs)
	Line 4978:     <arc exit="go" move="search go alcove" destination="745" />
From #737:
You scan the cave's shadows and find a small alcove! (NO RT) ($roomobjs)
	Line 5003:     <arc exit="go" move="search go alcove" destination="745" />
From #741:
You walk around the perimeter of the cave and discover a hidden alcove! (NO RT) ($roomobjs)

...Maps\Map9b_Sorrow's_Reach.xml (1 hit)
	Line 57:     <arc exit="go" move="search go overgrown path" destination="8" />
Unable to test this due to starting room being a "new map" node.

...Maps\Map66_STR3.xml (2 hits)
	Line 1362:     <arc exit="go" move="search go dirt path" destination="281" />
You search around for a moment.
Roundtime: 3 sec.
You find a dirt path! ($roomobjs)
	Line 2106:     <arc exit="go" move="search go onyx arch" destination="320" />
As you search, the air shimmers and a dark onyx arch appears! (NO RT) ($roomobjs)

...Maps\Map67_Shard.xml (1 hit)
	Line 227:     <arc exit="go" move="search go bank" hidden="True" destination="378" />
Just under the Bridge of Sparrows you notice a partially concealed channel bank. (NO RT)

...Maps\Map69_Shard_West_Gate.xml (1 hit)
	Line 42:     <arc exit="go" move="search go narrow path" destination="362" />
You search around for a moment.
Roundtime: 3 sec.
You find a narrow path. ($roomobjs)

UNTESTED:

...Maps\Map48_Haizen_Cugis.xml (1 hit)
	Line 16:     <arc exit="go" move="search go overgrown trail" destination="4" />

...Maps\Map106_Hara'jaal.xml (1 hit)
	Line 35:     <arc exit="none" move="search;#send 4 go shadowed opening" destination="9" />

...Maps\Map108_M'Riss.xml (1 hit)
	Line 2421:     <arc exit="none" move="search; climb footholds" destination="355" />

...Maps\Map90_Ratha.xml (1 hit)
	Line 5186:     <arc exit="none" move="search go wall panel" destination="799" />

...Maps\Map92_Ratha_NW.xml (2 hits)
	Line 604:     <arc exit="go" move="search go narrow gap" destination="109" />
	Line 1339:     <arc exit="go" move="search go trapdoor" destination="211" />

...Maps\Map98_Road_to_Aesry.xml (3 hits)
	Line 232:     <arc exit="go" move="rt search;-2 go dark opening" destination="36" />
	Line 1071:     <arc exit="none" move="rt search;go fallen log" destination="168" />
	Line 2034:     <arc exit="none" move="rt search;go door" destination="336" />

**Comment by HanryuDR** [comment]
from PELIC
https://discord.com/channels/481893424359014411/630143842376613928/1037415919338663989
#### Find the stupid path to Sorrow's Reach
SorrowsReach:
     # debuglevel 10
Checkroom:
     pause 0.5
     if matchre("$roomobjs", "a small overgrown path") then goto SorrowsReachMoveOn
     else goto Search
Search:
     matchre Search ^\.\.\.wait|^Sorry\,
     matchre SorrowsReachMoveOn ^There seems to be some sort of path leading to the east\.
     matchre Checkroom ^You search around for a moment\.
     send search
     matchwait
SorrowsReachMoveOn:
     send go path
     waitforre ^The path underfoot is overgrown with weeds and almost completely covered with dried\, fallen branches yet still feels surprisingly firm\.
     pause
     put #parse MOVE SUCCESSFUL
     exit
#### EOF

**Comment by TendyVittles** [comment]
My own version of that, just for the point path logic...

FIND_SUNFALL:
pause 0.2
if matchre ("$roomobjs","a stony trail and a weathered obsidian marker") then goto SEARCH_PATH
#flow into...
# (That could have been ... if !matchre ($roomobjs","a small overgrown path") then...

POINT_PATH:
pause 0.2
put point path
matchre POINT_PATH ^\.\.\.wait|^Sorry\,
matchre PATH_FOUND ^You point at a small overgrown path, revealing it to everyone.
matchre SEARCH_PATH ^I could not find what you were referring to
matchwait

SEARCH_PATH:
pause 0.2
put search
matchre SEARCH_PATH ^\.\.\.wait|^Sorry\,|^You search around for a moment\.
matchre POINT_PATH ^There seems to be some sort of path leading to the east|^You don't find anything of interest here
matchwait

PATH_FOUND:
move go path

**Comment by Azothy** [comment]
All instances tested and fixed in latest Automapper and maps
