### ISSUE TITLE
gear gate double wait

### ISSUE THREAD

**Issue by HanryuDR** [GenieClient/Maps#41]
TenderVittles — Today at 12:49 AM
The maze of interlocking cogs and sprockets set into the face of the massive gear gate grind to a stuttering halt as it slides to a fully open position with a creaking *THUD*.

A fur-clad Dwarven guard bellows, "The gear gate is open, second guard take up a defensive position and stand ready!"
> go gate
A fur-clad Dwarven guard gazes down at you with an apprising expression before briskly waving you though the massive gear gate with a gauntleted hand.
 
Recently went through the Gear Gate... had to wait twice because automapper didn't go through when it opened the first time.
Making a note of it to help me remember to get back into the swing of things after festival stress is gone

**Comment by Azothy** [comment]
Subscript for getting in/out of Gear Gate was added in previous update
