### ISSUE TITLE
Use darkvision tools when stuck in dark rooms

### ISSUE THREAD

**Issue by HanryuDR** [GenieClient/Maps#66]
question: Is there a trigger in travel/automapper that I could script off of for when you can't see anything in the room and it's 0,0 as it's lost 

if error && darkroom
https://elanthipedia.play.net/Guilds_kit_at_a_glance#Utility

**Comment by HanryuDR** [comment]
if (($roomid = 0) && ($zoneid = 13)) then gosub CHECK_DARK

## ****
CHECK_DARK:
        matchre YEP_DARK It's pitch dark and you can't see a thing!
    send look
    matchwait 3
    return
    
    ## *****
    YEP_DARK:
        send charge my %gaeth_type 100
         wait 5
        send focus my %gaeth_type
        wait 3
        send rub my %gaeth_type
        wait 3
        gosub RANDOM_DIR_MOVE
        return
##@ *****
RANDOM_DIR_MOVE:
    action (random_room) setvar obvious_exit $1 when ^Obvious exits: (\S+)\.
    action (random_room) setvar obvious_exit $1 when ^Obvious exits: (\S+)\,
    action (random_room) setvar obvious_exit $1 when ^Obvious paths: (\S+)\.
    action (random_room) setvar obvious_exit $1 when ^Obvious paths: (\S+)\,
    action (random_room) on
    pause .2
    send look
    pause .2
    send %obvious_exit
    pause .5
    action (random_room) off
    return

**Comment by Azothy** [comment]
https://pastebin.com/EgL85i6e
https://pastebin.com/qZV9x2u5
Will check for all known sources of DarkVision / Light Source tools as backup in next patch
