### ISSUE TITLE
Automapper/Travel persistent issue from Shard to Hibarnhvidar

### ISSUE THREAD

**Issue by SmoothMole** [GenieClient/Maps#93]
Persistent travel issue when starting at shard and traveling to Hibarnhvidar (map:116 | room:23).

It gets stuck here for 10 minutes:

[PersistentAutoMapperFault_283_Shard.txt](https://github.com/GenieClient/Maps/files/13705147/PersistentAutoMapperFault_283_Shard.txt)

[Seord Kerwaith, Mountain Road]
Small bits of wood and discarded food scraps rest at the foot of the canyon walls, covered in a thick layer of clear ice.  
travel.cmd(248): [var Moving 1]
Obvious paths: south, northwest.
> 
travel.cmd(6159): [MOVE_RETURN:]
travel.cmd(6160): [var moved 1]
travel.cmd(6161): [var randomloop 0]
travel.cmd(6162): [delay 0.00001]
travel.cmd(6163): [unvar moveloop]
travel.cmd(6164): [unvar movefailCounter]
travel.cmd(6165): [return]
travel.cmd(6513): [if ((4 = 4) && (0) && ("north" != "northwest")) then]
travel.cmd(6514): [if ((4 = 4) && (0) && ("north" != "northeast")) then]
travel.cmd(6515): [if (1 = 1) then]
travel.cmd(6515): [return]
travel.cmd(6010): [goto AUTOMOVE_GO]
travel.cmd(5974): [delay 0.00001]
travel.cmd(5975): [matchre AUTOMOVE_FAILED ^(?:AUTOMAPPER )?MOVE(?:MENT)? FAILED]
travel.cmd(5976): [matchre AUTOMOVE_RETURN ^YOU HAVE ARRIVED(?:\!)?]
travel.cmd(5977): [matchre AUTOMOVE_RETURN ^SHOP CLOSED(?:\!)?]
travel.cmd(5978): [matchre AUTOMOVE_FAIL_BAIL ^DESTINATION NOT FOUND]
travel.cmd(5979): [matchre AUTOMOVE_FAILED ^You don't seem]
travel.cmd(5980): [put #goto 283]
[AutoMapper] Destination ID #283 not found - your current location is unknown.
travel.cmd(5981): [matchwait 3]
travel.cmd(5982): [if (1 = 0) then]
travel.cmd(5983): [matchre AUTOMOVE_FAILED ^(?:AUTOMAPPER )?MOVE(?:MENT)? FAILED]
travel.cmd(5984): [matchre AUTOMOVE_RETURN ^YOU HAVE ARRIVED(?:\!)?]
travel.cmd(5985): [matchre AUTOMOVE_RETURN ^SHOP CLOSED(?:\!)?]
travel.cmd(5986): [matchre AUTOMOVE_FAIL_BAIL ^DESTINATION NOT FOUND]
travel.cmd(5987): [matchwait 180]

**Comment by Azothy** [comment]
Fixt
